# Generated by Django 3.2.8 on 2021-10-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='course',
        ),
    ]
