# Generated by Django 3.2.8 on 2021-10-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_mycourse_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
