# Generated by Django 3.2.8 on 2021-10-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flearn', '0004_alter_subcategory_slug'),
        ('account', '0004_auto_20211008_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycourse',
            old_name='user',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='mycourse',
            name='name',
        ),
        migrations.AddField(
            model_name='mycourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='flearn.course'),
        ),
    ]
