# Generated by Django 3.2.8 on 2021-10-09 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20211008_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='student',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
