# Generated by Django 3.2.8 on 2021-10-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flearn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
